### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined in utils.getLabelFromKey

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#55] opened 2020-02-11 08:51 UTC
not investigated for the root cause but here is a stack appearing in Debug console:

```
TypeError: Cannot read property 'toUpperCase' of undefined
	at Object.getLabelFromKey (/home/apupier/git/vscode-datavirt/out/utils.js:48:13)
	at DataSourceTreeNode.initialize (/home/apupier/git/vscode-datavirt/out/model/tree/DataSourceTreeNode.js:43:31)
	at /home/apupier/git/vscode-datavirt/out/model/tree/DataSourcesTreeNode.js:72:21
	at Map.forEach (<anonymous>)
	at DataSourcesTreeNode.initialize (/home/apupier/git/vscode-datavirt/out/model/tree/DataSourcesTreeNode.js:68:15)
	at DVProjectTreeNode.initialize (/home/apupier/git/vscode-datavirt/out/model/tree/DVProjectTreeNode.js:51:30)
	at new DVProjectTreeNode (/home/apupier/git/vscode-datavirt/out/model/tree/DVProjectTreeNode.js:29:14)
	at DataVirtNodeProvider.processDataVirtYAML (/home/apupier/git/vscode-datavirt/out/model/tree/DataVirtNodeProvider.js:127:35)
	at DataVirtNodeProvider.processFile (/home/apupier/git/vscode-datavirt/out/model/tree/DataVirtNodeProvider.js:141:14)
	at /home/apupier/git/vscode-datavirt/out/model/tree/DataVirtNodeProvider.js:96:26
	at Array.forEach (<anonymous>)
	at DataVirtNodeProvider.<anonymous> (/home/apupier/git/vscode-datavirt/out/model/tree/DataVirtNodeProvider.js:94:44)
	at Generator.next (<anonymous>)
	at /home/apupier/git/vscode-datavirt/out/model/tree/DataVirtNodeProvider.js:8:71
	at new Promise (<anonymous>)
	at /home/apupier/git/vscode-datavirt/out/model/tree/DataVirtNodeProvider.js:4:12
	at /home/apupier/git/vscode-datavirt/out/model/tree/DataVirtNodeProvider.js:92:49
	at new Promise (<anonymous>)
	at DataVirtNodeProvider.refresh (/home/apupier/git/vscode-datavirt/out/model/tree/DataVirtNodeProvider.js:92:16)
	at /home/apupier/git/vscode-datavirt/out/extension.js:301:36
	at Generator.next (<anonymous>)
	at /home/apupier/git/vscode-datavirt/out/extension.js:24:71
	at new Promise (<anonymous>)
	at /home/apupier/git/vscode-datavirt/out/extension.js:20:12
	at /home/apupier/git/vscode-datavirt/out/extension.js:299:50
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at p.setVisible (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:523:162)
	at Object.$setVisible (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:519:422)
	at p._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:663:275)
	at p._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:662:971)
	at p._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:661:639)
	at p._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:660:468)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:658:691
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820:285
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
	at Object._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:193:629)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:190:824
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at p.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:737)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:89
	at Socket.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:195:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by lhein** [comment] 2020-02-17 11:31
Is there a way to reproduce the error?

**Comment by apupier** [comment] 2020-02-17 11:58
> Is there a way to reproduce the error?

not found steps to reproduce

**Comment by lhein** [comment] 2020-02-20 19:16
I am not able to reproduce that issue after my latest PRs. Closing as fixed. Please reopen if you encounter it still with latest sources.

**Closed by lhein** 2020-02-20 19:16 UTC
